(async()=>{
  const $=s=>document.querySelector(s),type=document.body.dataset.albumType;
  if(!type||!window.SUY_ADMIN)return;
  await (window.SUY_ADMIN_READY||Promise.resolve());
  const {loadContent,saveContent,uploadPublic,isAdmin}=window.SUY_ADMIN;
  let payload=await loadContent(`albums:${type}`).catch(()=>null)||{albums:[]};
  let albums=Array.isArray(payload.albums)?payload.albums:[],editingImages=[];
  const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const render=async()=>{const admin=await isAdmin(),root=$('#albums');root.innerHTML='';$('#albums-empty').hidden=albums.length>0;albums.forEach((album,index)=>{const images=album.images||[],article=document.createElement('article');article.className='album-card';article.innerHTML=`<div class="album-cover">${images[0]?`<img src="${safe(images[0])}" alt="">`:'<span>NO IMAGE</span>'}</div><div class="album-meta"><small>${String(index+1).padStart(2,'0')}</small><h2>${safe(album.title||'UNTITLED')}</h2><p>${safe(album.description||'')}</p><div><button type="button" data-open="${safe(album.id)}">OPEN</button>${admin?`<button type="button" data-edit="${safe(album.id)}">EDIT</button><button type="button" data-delete="${safe(album.id)}">DELETE</button>`:''}</div></div><div class="album-images" hidden>${images.map((src,i)=>`<img src="${safe(src)}" alt="${safe(album.title||'Album')} ${i+1}">`).join('')}</div>`;root.append(article)});root.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const g=b.closest('.album-card').querySelector('.album-images');g.hidden=!g.hidden});root.querySelectorAll('.album-images img').forEach(i=>i.onclick=()=>{$('#album-lightbox-image').src=i.src;$('#album-lightbox').showModal()});root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this album?'))return;albums=albums.filter(a=>a.id!==b.dataset.delete);await saveContent(`albums:${type}`,{albums});await render()})};
  const preview=()=>{$('#album-image-preview').innerHTML=editingImages.map((src,i)=>`<figure><img src="${safe(src)}" alt=""><button type="button" data-remove-image="${i}">×</button></figure>`).join('');document.querySelectorAll('[data-remove-image]').forEach(b=>b.onclick=()=>{editingImages.splice(Number(b.dataset.removeImage),1);preview()})};
  const openEditor=()=>{$('#album-editor').hidden=false;document.body.classList.add('editor-open');$('#album-editor').scrollIntoView({behavior:'smooth'})};
  const resetEditor=()=>{$('#album-id').value='';$('#album-title').value='';$('#album-description').value='';$('#album-images').value='';editingImages=[];preview()};
  const edit=id=>{const album=albums.find(a=>a.id===id);if(!album)return;$('#album-id').value=album.id;$('#album-title').value=album.title||'';$('#album-description').value=album.description||'';editingImages=[...(album.images||[])];preview();openEditor()};
  $('#new-album').onclick=async()=>{if(!await isAdmin())return;resetEditor();openEditor()};$('#close-album-editor').onclick=()=>{$('#album-editor').hidden=true;document.body.classList.remove('editor-open')};
  $('#album-images').onchange=async e=>{if(!await isAdmin())return;$('#album-status').textContent='UPLOADING...';for(const file of e.target.files){try{editingImages.push(await uploadPublic(file,`albums/${type}`))}catch(err){alert('UPLOAD FAILED: '+err.message)}}e.target.value='';preview();$('#album-status').textContent=''};
  $('#save-album').onclick=async()=>{if(!await isAdmin())return;const title=$('#album-title').value.trim();if(!title){$('#album-status').textContent='PLEASE ENTER AN ALBUM NAME.';return}const id=$('#album-id').value||`${Date.now()}-${Math.random().toString(16).slice(2)}`,album={id,title,description:$('#album-description').value.trim(),images:[...editingImages]},at=albums.findIndex(a=>a.id===id);if(at>=0)albums[at]=album;else albums.unshift(album);try{await saveContent(`albums:${type}`,{albums});$('#album-status').textContent='SAVED TO SUPABASE.';$('#album-editor').hidden=true;document.body.classList.remove('editor-open');await render()}catch(err){$('#album-status').textContent='SAVE FAILED: '+err.message}};
  $('#close-album-lightbox').onclick=()=>$('#album-lightbox').close();
  await render();
})();
