(() => {
  const $ = s => document.querySelector(s);
  const pad=n=>String(n).padStart(2,'0');
  const today=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
  const id=()=>crypto.randomUUID?.()||`day-${Date.now()}-${Math.random()}`;
  const fonts={hand:"'Caveat','Nanum Pen Script',cursive",pen:"'Nanum Pen Script',cursive",cute:"'Gaegu',cursive",serif:"'Cormorant Garamond',serif",sans:"'Noto Sans SC',sans-serif",mono:"'DM Mono',monospace"};
  let payload={items:[]},items=[],cursor=new Date(),activeId='';cursor.setDate(1);
  const dialog=$('#calendar-detail'),form=$('#diary-form'),editor=$('#diary-dialog');
  const valid=s=>/^\d{4}-\d{2}-\d{2}$/.test(s||'');
  function render(){const year=cursor.getFullYear(),month=cursor.getMonth(),grid=$('#diary-calendar-grid');$('#diary-calendar-month').textContent=new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(cursor).toUpperCase();grid.replaceChildren();const offset=new Date(year,month,1).getDay(),days=new Date(year,month+1,0).getDate();for(let n=0;n<Math.ceil((offset+days)/7)*7;n++){const day=n-offset+1,cell=document.createElement(day>0&&day<=days?'button':'span');cell.className=day>0&&day<=days?'calendar-cell':'calendar-blank';if(day>0&&day<=days){const date=`${year}-${pad(month+1)}-${pad(day)}`,entries=items.filter(x=>x.date===date);cell.type='button';cell.setAttribute('aria-label',`${date}${entries.length?`, ${entries.length} entries`:''}`);const num=document.createElement('span');num.className='calendar-number';num.textContent=pad(day);cell.append(num);if(entries.length){const entry=entries[0],photos=Array.isArray(entry.images)?entry.images:(entry.image?[entry.image]:[]);if(photos[0]){const img=document.createElement('img');img.src=photos[0];img.loading='lazy';img.alt='';cell.append(img)}const title=document.createElement('span');title.className='calendar-snippet';title.textContent=entry.title||entry.text||'';title.style.fontFamily=fonts[entry.style?.font]||fonts.hand;cell.append(title);if(entries.length>1){const count=document.createElement('span');count.className='calendar-count';count.textContent=`+${entries.length-1}`;cell.append(count)}}cell.onclick=()=>{if(entries.length)show(date,entries);else if(window.SUY_IS_ADMIN)openEditor(null,date)};}grid.append(cell)}}
  function show(date,entries){const root=$('#calendar-detail-body');root.replaceChildren();const heading=document.createElement('h2');heading.textContent=date;root.append(heading);entries.forEach(entry=>{const section=document.createElement('article');section.className='calendar-entry';if(entry.title){const h=document.createElement('h3');h.textContent=entry.title;section.append(h)}const photos=Array.isArray(entry.images)?entry.images:(entry.image?[entry.image]:[]);if(photos.length){const gallery=document.createElement('div');gallery.className='calendar-detail-photos';photos.forEach(src=>{const img=document.createElement('img');img.src=src;img.alt='Calendar photo';gallery.append(img)});section.append(gallery)}const p=document.createElement('p');p.textContent=entry.text||'';p.style.fontFamily=fonts[entry.style?.font]||fonts.hand;p.style.fontSize=`${Math.min(64,Math.max(14,Number(entry.style?.size)||20))}px`;p.style.color=entry.style?.color||'#777';section.append(p);if(window.SUY_IS_ADMIN){const b=document.createElement('button');b.type='button';b.textContent='EDIT ↗';b.onclick=()=>{dialog.close();openEditor(entry)};section.append(b)}root.append(section)});dialog.showModal()}
  function openEditor(entry=null,date=today()){form.reset();activeId=entry?.id||'';$('#diary-edit-id').value=activeId;$('#diary-date').value=entry?.date||date;$('#diary-title').value=entry?.title||'';$('#diary-text').value=entry?.text||'';$('#diary-font').value=entry?.style?.font||'hand';$('#diary-size').value=entry?.style?.size||'';$('#diary-color').value=entry?.style?.color||'#777777';$('#diary-color-hex').value=$('#diary-color').value.toUpperCase();$('#diary-existing-photos').replaceChildren();const photos=entry?.images||(entry?.image?[entry.image]:[]);photos.forEach(src=>{const img=document.createElement('img');img.src=src;img.alt='Existing photo';$('#diary-existing-photos').append(img)});$('#diary-existing-photos').hidden=!photos.length;$('#diary-remove-photo-wrap').hidden=!photos.length;$('#diary-editor-status').textContent='';preview();manager();editor.showModal()}
  function preview(){const p=$('#diary-style-preview');p.textContent=$('#diary-text').value||'Write here…';p.style.fontFamily=fonts[$('#diary-font').value]||fonts.hand;p.style.fontSize=($('#diary-size').value||20)+'px';p.style.color=$('#diary-color').value}
  function manager(){const root=$('#diary-manager');root.replaceChildren();$('#diary-manager-count').textContent=pad(items.length);[...items].reverse().forEach(entry=>{const row=document.createElement('div');row.className='diary-row';const name=document.createElement('span');name.textContent=`${entry.date} · ${entry.title||entry.text?.slice(0,25)||''}`;const edit=document.createElement('button');edit.type='button';edit.textContent='EDIT';edit.onclick=()=>openEditor(entry);const del=document.createElement('button');del.type='button';del.textContent='DELETE';del.onclick=async()=>{if(!confirm(`Delete ${entry.date}?`)||!await window.SUY_ADMIN.isAdmin())return;try{await save(items.filter(x=>x.id!==entry.id));manager()}catch(e){$('#diary-editor-status').textContent=e.message}};row.append(name,edit,del);root.append(row)})}
  async function save(next){await window.SUY_ADMIN.saveContent('diary',{...payload,items:next});items=next;payload={...payload,items};render()}
  $('#diary-calendar-prev').onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()-1,1);render()};$('#diary-calendar-next').onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()+1,1);render()};
  $('#edit-diary').onclick=async()=>{if(await window.SUY_ADMIN.isAdmin())openEditor()};$('#diary-new-draft').onclick=()=>openEditor();$('#close-diary-editor').onclick=()=>editor.close();dialog.querySelector('.close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};editor.onclick=e=>{if(e.target===editor)editor.close()};
  ['diary-text','diary-font','diary-size'].forEach(key=>$('#'+key).oninput=preview);$('#diary-color').oninput=()=>{$('#diary-color-hex').value=$('#diary-color').value.toUpperCase();preview()};$('#diary-color-hex').oninput=()=>{if(/^#[a-f\d]{6}$/i.test($('#diary-color-hex').value)){$('#diary-color').value=$('#diary-color-hex').value;preview()}};
  form.onsubmit=async e=>{e.preventDefault();const status=$('#diary-editor-status');try{if(!await window.SUY_ADMIN.isAdmin())throw Error('Admin login required');const date=$('#diary-date').value,text=$('#diary-text').value.trim();if(!valid(date))throw Error('Choose a date');if(!text&&!$('#diary-images').files.length)throw Error('Add text or a photo');const existing=items.find(x=>x.id===activeId);let images=$('#diary-remove-photo').checked?[]:[...(existing?.images||(existing?.image?[existing.image]:[]))];const files=[...$('#diary-images').files];if(files.length+images.length>4)throw Error('Up to four photos per date');for(const file of files){status.textContent='UPLOADING…';images.push(await window.SUY_ADMIN.uploadPublic(file,'diary'))}const entry={...existing,id:activeId||id(),date,title:$('#diary-title').value.trim(),text,images,image:images[0]||'',style:{font:$('#diary-font').value,size:$('#diary-size').value,color:$('#diary-color').value}};status.textContent='SAVING…';await save([...items.filter(x=>x.id!==activeId),entry].sort((a,b)=>a.date.localeCompare(b.date)));cursor=new Date(Number(date.slice(0,4)),Number(date.slice(5,7))-1,1);render();editor.close()}catch(error){status.textContent=error.message}};
  (async()=>{try{if(window.SUY_SITE_READY)await window.SUY_SITE_READY;payload=await window.SUY_ADMIN.loadContent('diary')||{items:[]};items=Array.isArray(payload.items)?payload.items:[];render()}catch(e){console.warn('Calendar unavailable',e);render()}})();
})();
