(() => {
  const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const defaults={title:'고양이의 작은 방',intro:'책장을 열면, 우리의 작은 하루가 시작돼요.',cat:'안녕! 내 방에 온 걸 환영해. 잠깐 같이 쉬어 갈래?',window:'창가에 앉아 햇살을 모으는 중이에요. 오늘은 어떤 하루였나요?',birthday:'내 생일은 5월 5일이에요. 함께해 주는 모든 날이 선물 같아요.',album:'사진 속에 담긴 작은 순간들을 천천히 살펴봐요.',treat:'간식을 받았어요. 오늘도 다정한 마음을 고마워요!',labels:{room:'우리의 작은 공간',birthdayHeader:'05 / 05 · 고양이의 생일',photoHint:'소중한 순간을 담아 주세요',cat:'고양이에게 인사하기',window:'창가의 이야기',birthday:'5월 5일 · 생일',album:'우리의 사진첩',treat:'간식 주기',pages:'책장 보기',print:'오늘의 마음 인쇄',enter:'고양이의 방으로'},photos:[]};
  let data=structuredClone(defaults),active='cat',opened=false,lastClosed=true,openingTimer=null;
  const book=$('#about-book');
  const scene=document.createElement('section');scene.className='cat-room-scene';scene.hidden=true;scene.setAttribute('aria-label','고양이의 작은 방');book.append(scene);
  const entry=document.createElement('button');entry.type='button';entry.className='cat-room-entry';entry.hidden=true;entry.textContent=defaults.labels.enter;$('.book-admin-actions').before(entry);
  const editor=document.createElement('dialog');editor.className='stationery-dialog cat-room-editor';editor.innerHTML='<button class="close" type="button" aria-label="닫기">×</button><h2>고양이의 방 편집</h2><form id="cat-room-edit-form"></form>';document.body.append(editor);editor.querySelector('.close').onclick=()=>editor.close();
  const photoURL=v=>{if(!v||!String(v).trim())return '';try{const u=new URL(v,location.href);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};
  function render(){scene.innerHTML=`<div class="cat-room-left"><span class="room-eyebrow">${esc(data.labels.room)}</span><div class="room-drawing"><svg viewBox="0 0 500 460" aria-hidden="true"><g fill="none" stroke="#747976" stroke-width="1.4"><path d="M40 360H470M62 355V83H223V355M62 210H223M142 83V354M58 78H228M51 66Q73 190 43 325M235 66Q213 190 242 325M270 364L282 320H339L348 364M291 321Q266 272 283 250Q310 267 311 319M321 320Q349 275 338 244Q316 264 318 318M68 372L77 411H218L230 372M82 400H221"/><path d="M340 105H446V182H340Z M332 185H454 M344 111L440 177 M440 111L344 177"/></g></svg><button class="room-hotspot room-window" data-room="window" aria-label="${esc(data.labels.window)}"><span>${esc(data.labels.window)}</span></button><button class="room-hotspot room-cat" data-room="cat"><img src="assets/cat-signature.png" alt="고양이"><span>${esc(data.labels.cat)}</span></button><button class="room-hotspot room-birthday" data-room="birthday"><span class="birthday-date">05 / 05</span><span>${esc(data.labels.birthday)}</span></button><button class="room-hotspot room-album" data-room="album"><span class="album-lines" aria-hidden="true"></span><span>${esc(data.labels.album)}</span></button></div><div class="room-photo-strip">${Array.from({length:3},(_,i)=>`<button type="button" data-room-photo="${i}" class="room-print-photo" aria-label="사진 ${i+1}">${photoURL(data.photos[i])?`<img src="${esc(photoURL(data.photos[i]))}" alt="우리의 사진 ${i+1}">`:`<span>사진 ${String(i+1).padStart(2,'0')}<small>${esc(data.labels.photoHint)}</small></span>`}</button>`).join('')}</div></div><div class="cat-room-right"><span class="room-eyebrow">${esc(data.labels.birthdayHeader)}</span><h2>${esc(data.title)}</h2><p class="room-intro">${esc(data.intro)}</p><div class="room-story" aria-live="polite"><span class="room-story-mark" aria-hidden="true">⌁</span><p id="room-story-text">${esc(data[active])}</p></div><button class="room-treat" data-room="treat">${esc(data.labels.treat)} <span aria-hidden="true">♡</span></button><div class="room-bottom"><button id="room-pages">${esc(data.labels.pages)} ↗</button><button id="room-print">${esc(data.labels.print)} ↗</button><button id="room-edit" data-admin-only ${window.SUY_IS_ADMIN?'':'hidden'}>이 공간 편집</button></div></div>`;
    scene.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>tell(b.dataset.room));
    scene.querySelectorAll('[data-room-photo]').forEach(b=>b.onclick=()=>{const src=photoURL(data.photos[Number(b.dataset.roomPhoto)]);if(src){const d=$('#book-photo-dialog');d.querySelector('img').src=src;d.showModal()}else tell('album')});
    $('#room-pages').onclick=()=>{scene.hidden=true;opened=false;entry.hidden=false};$('#room-print').onclick=()=>$('.paper-open').click();$('#room-edit').onclick=edit;
    entry.textContent=data.labels.enter;
  }
  function tell(key){active=key;const p=$('#room-story-text');p.textContent=data[key]||'';p.classList.remove('story-arrives');void p.offsetWidth;p.classList.add('story-arrives');scene.querySelectorAll('[data-room]').forEach(b=>b.classList.toggle('selected',b.dataset.room===key));if(key==='treat'){scene.classList.remove('cat-is-happy');void scene.offsetWidth;scene.classList.add('cat-is-happy')}}
  function enter(){if(book.classList.contains('is-closed'))return;opened=true;entry.hidden=true;scene.hidden=false;render();}
  entry.onclick=enter;
  document.addEventListener('notebook-section',e=>{const closed=e.detail.closed;if(closed){clearTimeout(openingTimer);scene.hidden=true;entry.hidden=true;opened=false;}else if(lastClosed){clearTimeout(openingTimer);openingTimer=setTimeout(enter,1150)}else if(e.detail.tab!=='cat'){scene.hidden=true;opened=false;entry.hidden=true}else if(!opened)entry.hidden=false;lastClosed=closed;});
  document.addEventListener('suyoon-admin-state',()=>{const b=$('#room-edit');if(b)b.hidden=!window.SUY_IS_ADMIN});
  async function edit(){if(!await window.SUY_ADMIN?.isAdmin())return;const form=$('#cat-room-edit-form'),fields=[['title','제목'],['intro','소개'],['cat','고양이의 인사'],['window','창가 이야기'],['birthday','생일 이야기 · 5월 5일'],['album','사진첩 이야기'],['treat','간식 이야기']];form.innerHTML=fields.map(([key,label])=>`<label>${label}<textarea name="${key}" rows="2" maxlength="1200">${esc(data[key])}</textarea></label>`).join('')+'<h3>버튼 문구</h3>'+Object.entries(data.labels).map(([key,value])=>`<label>${esc(defaults.labels[key])}<input name="label-${key}" value="${esc(value)}" maxlength="100"></label>`).join('')+'<h3>사진 업로드</h3>'+Array.from({length:3},(_,i)=>`<label>사진 ${i+1}<input name="photo-${i}" type="file" accept="image/jpeg,image/png,image/webp">${photoURL(data.photos[i])?`<img class="room-admin-preview" src="${esc(photoURL(data.photos[i]))}" alt="사진 ${i+1}"><label><input name="remove-${i}" type="checkbox">사진 비우기</label>`:''}</label>`).join('')+'<button type="submit">저장하기</button><p id="room-edit-status" role="status"></p>';form.onsubmit=save;editor.showModal();}
  async function save(e){e.preventDefault();const status=$('#room-edit-status');try{if(!await window.SUY_ADMIN.isAdmin())throw Error('관리자 로그인이 필요해요.');status.textContent='저장 중…';const form=new FormData(e.target),next=structuredClone(data);for(const key of ['title','intro','cat','window','birthday','album','treat'])next[key]=String(form.get(key)||'');for(const key of Object.keys(defaults.labels))next.labels[key]=String(form.get('label-'+key)||defaults.labels[key]);for(let i=0;i<3;i++){if(form.get('remove-'+i))next.photos[i]='';const file=form.get('photo-'+i);if(file?.size){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024)throw Error('사진은 JPG, PNG, WebP 형식, 10MB 이하로 올려 주세요.');next.photos[i]=await window.SUY_ADMIN.uploadPublic(file,'cat-room')}}await window.SUY_ADMIN.saveContent('cat-room-scene',next);data=next;render();editor.close();}catch(error){status.textContent=error.message}}
  render();(async()=>{try{if(window.SUY_SITE_READY)await window.SUY_SITE_READY;const saved=await window.SUY_ADMIN.loadContent('cat-room-scene');data={...defaults,...saved,labels:{...defaults.labels,...saved?.labels},photos:Array.isArray(saved?.photos)?saved.photos:[]};render()}catch(error){console.warn('Cat room unavailable',error)}})();
})();
