(() => {
  const $=s=>document.querySelector(s);
  const safeURL=value=>{try{const u=new URL(value,location.href);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};
  const fonts={english:"'Agdasima','Nanum Barunpen','ChillHuoFangSong'",korean:"'Nanum Barunpen','ChillHuoFangSong','Agdasima'",chinese:"'ChillHuoFangSong','Nanum Barunpen','Agdasima'"};
  const options='<option value="english">English · Agdasima</option><option value="korean">한국어 · Nanum Barunpen</option><option value="chinese">中文 · 寒蝉活仿宋</option>';
  let settings={homeWords:'',catWords:'',homeStyle:{},catStyle:{},backgrounds:[]},noteKey='home',generated=null,printing=false,settingsReady=false,userPhoto=null;
  const date=()=>new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:'Asia/Seoul'}).format(new Date()).replace(/\//g,'-');
  function renderNote(){const p=$('#notebook-margin-text'),st=settings[noteKey+'Style']||{};p.textContent=settings[noteKey+'Words']||'';p.style.fontFamily=fonts[st.font]||fonts.english;p.style.fontSize=(Math.min(40,Math.max(14,Number(st.size)||23)))+'px';p.style.color=/^#[a-f\d]{6}$/i.test(st.color||'')?st.color:'#454545';p.style.textAlign=['left','center','right'].includes(st.align)?st.align:'left';$('.margin-caption').textContent=noteKey==='cat'?'DAYS WITH MY CAT':'A LITTLE NOTE';}
  document.addEventListener('notebook-section',e=>{const next=e.detail.closed?'home':e.detail.tab==='cat'?'cat':'home';if(next!==noteKey){noteKey=next;renderNote()}});
  document.body.insertAdjacentHTML('beforeend',`
    <dialog id="notebook-note-dialog" class="stationery-dialog"><form id="notebook-note-form"><button class="close" type="button" aria-label="Close">×</button><h2>WORDS IN THE MARGIN</h2><label>WORDS<textarea id="margin-words" rows="9" maxlength="2000"></textarea></label><div class="paper-controls"><label>FONT<select id="margin-font">${options}</select></label><label>SIZE<input id="margin-size" type="number" min="14" max="40" value="23"></label><label>COLOR<input id="margin-color" type="color" value="#454545"></label><label>ALIGN<select id="margin-align"><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></label></div><button type="submit">SAVE WORDS ↗</button><p class="paper-status" id="margin-status" role="status"></p></form></dialog>
    <dialog id="paper-dialog" class="stationery-dialog paper-dialog"><button class="close" type="button" aria-label="Close">×</button><h2 class="printer-title">A MOMENT, ON PAPER</h2><div class="paper-printer"><div class="printer-output"><canvas id="paper-canvas" width="1200" height="800" aria-label="Generated dated postcard"></canvas><div class="printer-empty" aria-hidden="true">YOUR MOMENT<br>STARTS HERE</div></div><div class="printer-slot" aria-hidden="true"></div><div class="printer-machine"><div class="printer-top" aria-hidden="true"></div><div class="printer-face"><form id="paper-form"><label class="visually-hidden" for="paper-words">YOUR WORDS</label><textarea id="paper-words" maxlength="600" rows="4" required placeholder="A feeling. A small moment. Something from today."></textarea><div class="printer-toolbar"><div class="paper-controls"><label class="postcard-photo-label">PHOTO · OPTIONAL<input id="paper-photo" type="file" accept="image/jpeg,image/png,image/webp"></label><label>DATE<input id="paper-date" type="date" required></label></div><button id="paper-generate" type="submit">PRINT</button></div><div id="paper-photo-preview" hidden><img alt="Your postcard photo"><span id="paper-photo-name"></span><button type="button" id="paper-photo-remove">REMOVE PHOTO</button></div><p class="paper-status" id="paper-status" role="status" aria-live="polite"></p></form></div><span class="printer-foot foot-left" aria-hidden="true"></span><span class="printer-foot foot-right" aria-hidden="true"></span></div><div class="printer-actions"><button id="paper-background-edit" type="button" data-admin-only hidden>PHOTO LIBRARY ↗</button><a id="paper-download" hidden download>DOWNLOAD JPG ↓</a></div></div></dialog>
    <dialog id="paper-background-dialog" class="stationery-dialog"><button class="close" type="button" aria-label="Close">×</button><h2>POSTCARD PHOTO LIBRARY</h2><p>Upload photos for everyone’s postcards. When no personal photo is selected, one library photo is chosen at random.</p><label>ADD PHOTOS<input id="paper-background-files" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><div id="paper-background-list"></div><p id="paper-background-status" class="paper-status" role="status"></p></dialog>
  `);
  for(const id of ['notebook-note-dialog','paper-dialog','paper-background-dialog']){const d=$('#'+id);d.querySelector('.close').onclick=()=>d.close();d.onclick=e=>{if(e.target===d)d.close()};}
  function showPaper(){$('#paper-date').value=date();$('#paper-dialog').showModal();$('#paper-words').focus();}
  document.querySelectorAll('.paper-open').forEach(b=>b.onclick=showPaper);
  async function showNote(){if(!await window.SUY_ADMIN?.isAdmin())return;const st=settings[noteKey+'Style']||{};$('#margin-words').value=settings[noteKey+'Words']||'';$('#margin-font').value=st.font||'english';$('#margin-size').value=st.size||23;$('#margin-color').value=st.color||'#454545';$('#margin-align').value=st.align||'left';$('#margin-status').textContent='';$('#notebook-note-dialog').showModal();}
  $('#notebook-note-edit').onclick=showNote;
  $('#notebook-margin-text').ondblclick=showNote;
  $('#notebook-note-form').onsubmit=async e=>{e.preventDefault();try{if(!await window.SUY_ADMIN?.isAdmin())throw Error('Admin login required');const next={...settings,[noteKey+'Words']:$('#margin-words').value,[noteKey+'Style']:{font:$('#margin-font').value,size:Number($('#margin-size').value),color:$('#margin-color').value,align:$('#margin-align').value}};await window.SUY_ADMIN.saveContent('notebook-settings',next);settings=next;renderNote();$('#notebook-note-dialog').close()}catch(error){$('#margin-status').textContent=error.message}};
  function listBackgrounds(){const root=$('#paper-background-list');root.replaceChildren();if(!settings.backgrounds.length){const empty=document.createElement('p');empty.textContent='Your photo library is empty. Add photos above to use them in postcards.';root.append(empty)}settings.backgrounds.forEach((url,i)=>{const row=document.createElement('div'),img=document.createElement('img'),remove=document.createElement('button');img.src=safeURL(url);img.alt='Paper background '+(i+1);remove.type='button';remove.textContent='REMOVE';remove.onclick=async()=>{if(!await window.SUY_ADMIN?.isAdmin())return;try{const next={...settings,backgrounds:settings.backgrounds.filter((_,n)=>n!==i)};await window.SUY_ADMIN.saveContent('notebook-settings',next);settings=next;listBackgrounds()}catch(error){$('#paper-background-status').textContent=error.message}};row.append(img,remove);root.append(row)});}
  $('#paper-background-edit').onclick=async()=>{if(!await window.SUY_ADMIN?.isAdmin())return;listBackgrounds();$('#paper-background-dialog').showModal()};
  $('#paper-background-files').onchange=async e=>{const status=$('#paper-background-status'),files=[...e.target.files];try{if(!await window.SUY_ADMIN?.isAdmin())throw Error('Admin login required');if(files.length+settings.backgrounds.length>24)throw Error('Up to 24 backgrounds');let uploaded=[];for(const file of files){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Choose JPG, PNG or WebP photos');if(file.size>10*1024*1024)throw Error('Each photo must be below 10 MB');status.textContent='UPLOADING…';uploaded.push(await window.SUY_ADMIN.uploadPublic(file,'paper-backgrounds'))}const next={...settings,backgrounds:[...settings.backgrounds,...uploaded]};await window.SUY_ADMIN.saveContent('notebook-settings',next);settings=next;listBackgrounds();status.textContent='SAVED';}catch(error){status.textContent=error.message}e.target.value='';};
  const language=text=>/[\uac00-\ud7af\u1100-\u11ff\u3130-\u318f]/u.test(text)?'korean':/\p{Script=Han}/u.test(text)?'chinese':'english';
  $('#paper-words').addEventListener('input',()=>$('#paper-words').style.setProperty('font-family',fonts[language($('#paper-words').value)],'important'));
  function readPhoto(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Could not read this photo.'));reader.readAsDataURL(file)});}
  $('#paper-photo').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024)throw Error('Choose a JPG, PNG or WebP photo below 10 MB.');const url=await readPhoto(file);await imageFrom(url,true);userPhoto=url;$('#paper-photo-preview img').src=url;$('#paper-photo-name').textContent=file.name;$('#paper-photo-preview').hidden=false;$('#paper-status').textContent='Your photo will be used for this postcard.';}catch(error){e.target.value='';$('#paper-status').textContent=error.message}};
  $('#paper-photo-remove').onclick=()=>{userPhoto=null;$('#paper-photo').value='';$('#paper-photo-preview').hidden=true;$('#paper-status').textContent='A photo will be chosen from the library.'};
  async function imageFrom(url,local=false){return new Promise((resolve,reject)=>{const img=new Image();if(!local)img.crossOrigin='anonymous';img.onload=()=>resolve(img);img.onerror=()=>reject(Error('Photo could not load. Please choose another photo.'));img.src=local?url:safeURL(url)});}
  function textRuns(text){const runs=[];let key='english';for(const ch of text){if(/[\uac00-\ud7af\u1100-\u11ff\u3130-\u318f]/u.test(ch))key='korean';else if(/\p{Script=Han}/u.test(ch))key='chinese';else if(/[A-Za-z0-9]/u.test(ch))key='english';if(runs.length&&runs[runs.length-1].key===key)runs[runs.length-1].text+=ch;else runs.push({key,text:ch})}return runs;}
  function measureWords(ctx,text,size){let width=0;for(const run of textRuns(text)){ctx.font=size+'px '+fonts[run.key];width+=ctx.measureText(run.text).width}return width;}
  function drawWords(ctx,text,x,y,size){for(const run of textRuns(text)){ctx.font=size+'px '+fonts[run.key];ctx.fillText(run.text,x,y);x+=ctx.measureText(run.text).width}}
  function fitPhoto(ctx,img,x,y,w,h){const scale=Math.min(w/img.width,h/img.height);ctx.fillStyle='#eeeeec';ctx.fillRect(x,y,w,h);ctx.drawImage(img,x+(w-img.width*scale)/2,y+(h-img.height*scale)/2,img.width*scale,img.height*scale);}
  function wrap(ctx,text,width){const lines=[];for(const paragraph of text.split('\n')){let line='';if(!paragraph){lines.push('');continue}for(const token of paragraph.match(/[A-Za-z0-9]+(?:['’-][A-Za-z0-9]+)*|[^A-Za-z0-9]/gu)||[]){if(ctx.measureText(token).width>width){for(const ch of token){if(ctx.measureText(line+ch).width>width&&line){lines.push(line.trimEnd());line=''}line+=ch;}}else if(ctx.measureText(line+token).width>width&&line){lines.push(line.trimEnd());line=token.trimStart()}else line+=token;}lines.push(line.trimEnd())}return lines;}
  function printFinish(){printing=false;$('.paper-printer').classList.remove('is-printing');$('#paper-generate').disabled=false;$('#paper-download').hidden=false;$('#paper-status').textContent='Your moment is ready.';}
  $('#paper-form').onsubmit=async e=>{e.preventDefault();if(printing)return;const text=$('#paper-words').value.trim();if(!text){$('#paper-status').textContent='Write a little moment first.';return}printing=true;$('#paper-generate').disabled=true;$('#paper-download').hidden=true;$('#paper-status').textContent='PREPARING PAPER…';try{
    if(!settingsReady)await ready;const canvas=$('#paper-canvas'),ctx=canvas.getContext('2d');ctx.fillStyle='#fafaf8';ctx.fillRect(0,0,1200,800);
    // Preview and JPEG share these intrinsic dimensions; never stretch the paper.
    let img=null;if(userPhoto)img=await imageFrom(userPhoto,true);else if(settings.backgrounds.length)img=await imageFrom(settings.backgrounds[Math.floor(Math.random()*settings.backgrounds.length)]);
    ctx.strokeStyle='#deded9';ctx.lineWidth=1;ctx.strokeRect(24.5,24.5,1151,751);
    if(img){fitPhoto(ctx,img,48,48,550,704);ctx.strokeStyle='#ddd';ctx.strokeRect(48.5,48.5,549,703);}
    const x=img?654:85,width=img?460:1030,family=fonts[language(text)];await Promise.all(textRuns(text).map(run=>document.fonts.load('40px '+fonts[run.key],run.text)));await document.fonts.load('28px Agdasima');
    ctx.fillStyle='#777';ctx.font='28px Agdasima';ctx.fillText($('#paper-date').value.replace(/-/g,'.'),x,112);
    ctx.strokeStyle='#bdbdb8';ctx.beginPath();ctx.moveTo(x,142);ctx.lineTo(x+width,142);ctx.stroke();
    let size=40,lines=[];do{ctx.font=size+'px '+family;lines=wrap({measureText:t=>({width:measureWords(ctx,t,size)})},text,width);if(lines.length*size*1.5<=480)break;size-=1}while(size>12);
    ctx.fillStyle='#333';lines.forEach((line,i)=>drawWords(ctx,line,x,207+i*size*1.5,size));
    ctx.font='22px Agdasima';ctx.fillStyle='#858581';ctx.fillText('A MOMENT, ON PAPER',x,713);ctx.strokeStyle='#888';ctx.strokeRect(1054.5,66.5,59,69);ctx.font='17px Agdasima';ctx.fillText('POST',1069,107);
    generated={url:canvas.toDataURL('image/jpeg',.95),name:'postcard-'+$('#paper-date').value+'.jpg'};$('#paper-download').href=generated.url;$('#paper-download').download=generated.name;
    const printer=$('.paper-printer');printer.classList.remove('is-printing');void printer.offsetWidth;printer.classList.add('has-paper','is-printing');$('#paper-status').textContent='PRINTING…';
    if(matchMedia('(prefers-reduced-motion:reduce)').matches)printFinish();else setTimeout(printFinish,4100);
  }catch(error){printing=false;$('#paper-generate').disabled=false;$('#paper-status').textContent=error.message}};

  const ready=(async()=>{try{if(window.SUY_SITE_READY)await window.SUY_SITE_READY;const [saved,old]=await Promise.all([window.SUY_ADMIN.loadContent('notebook-settings'),window.SUY_ADMIN.loadContent('about-book').catch(()=>null)]);settings={...settings,...saved};settings.backgrounds=(Array.isArray(settings.backgrounds)?settings.backgrounds:[]).map(safeURL).filter(Boolean);if(!saved?.homeWords&&old?.profile?.message)settings.homeWords=old.profile.message;renderNote();}catch(error){console.warn('Notebook settings unavailable',error)}finally{settingsReady=true}})();
  renderNote();
})();
